# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  node:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: cargo install blockset
    - run: npm test

  node-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: cargo install blockset
    - run: blockset add .\examples\list.txt
    - run: npm test

  deno:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: cargo install blockset
    - run: blockset add .\examples\list.txt
    # - run: deno run --quiet --allow-read --allow-env --allow-net --allow-hrtime ./test.mjs
    - run: deno run --quiet --allow-read ./test.mjs

  bun:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: curl -fsSL https://bun.sh/install | bash
    - run: cargo install blockset
    - run: blockset add .\examples\list.txt
    - run: /home/runner/.bun/bin/bun ./test.mjs
